class QuranSurahData {
  QuranSurahData._();

  static const int totalSurahs = 114;
  static const int totalVerses = 6236;
  static const int totalPages = 604;

  static const List<SurahInfo> surahs = [
    SurahInfo(1, 'الفَاتِحة', 'Al-Fātiḥah', 7, 'Meccan'),
    SurahInfo(2, 'البَقَرَة', 'Al-Baqarah', 286, 'Medinan'),
    SurahInfo(3, 'آل عِمران', 'Āl-‘Imrān', 200, 'Medinan'),
    SurahInfo(4, 'النِّسَاء', 'An-Nisā’', 176, 'Medinan'),
    SurahInfo(5, 'المَائدة', 'Al-Mā’idah', 120, 'Medinan'),
    SurahInfo(6, 'الأنعَام', 'Al-An‘ām', 165, 'Meccan'),
    SurahInfo(7, 'الأعرَاف', 'Al-A‘rāf', 206, 'Meccan'),
    SurahInfo(8, 'الأنفَال', 'Al-Anfāl', 75, 'Medinan'),
    SurahInfo(9, 'التوبَة', 'At-Taubah', 129, 'Medinan'),
    SurahInfo(10, 'يُونس', 'Yūnus', 109, 'Meccan'),
    SurahInfo(11, 'هُود', 'Hūd', 123, 'Meccan'),
    SurahInfo(12, 'يُوسُف', 'Yūsuf', 111, 'Meccan'),
    SurahInfo(13, 'الرَّعد', 'Ar-Ra‘d', 43, 'Medinan'),
    SurahInfo(14, 'إبراهِيم', 'Ibrāhīm', 52, 'Meccan'),
    SurahInfo(15, 'الحِجر', 'Al-Ḥijr', 99, 'Meccan'),
    SurahInfo(16, 'النَّحل', 'An-Naḥl', 128, 'Meccan'),
    SurahInfo(17, 'الإسرَاء', 'Al-Isrā’', 111, 'Meccan'),
    SurahInfo(18, 'الكَهف', 'Al-Kahf', 110, 'Meccan'),
    SurahInfo(19, 'مَريَم', 'Maryam', 98, 'Meccan'),
    SurahInfo(20, 'طه', 'Ṭā-Hā', 135, 'Meccan'),
    SurahInfo(21, 'الأنبيَاء', 'Al-Anbiyā’', 112, 'Meccan'),
    SurahInfo(22, 'الحج', 'Al-Ḥajj', 78, 'Medinan'),
    SurahInfo(23, 'المؤمنُون', 'Al-Mu’minūn', 118, 'Meccan'),
    SurahInfo(24, 'النور', 'An-Nūr', 64, 'Medinan'),
    SurahInfo(25, 'الفُرقَان', 'Al-Furqān', 77, 'Meccan'),
    SurahInfo(26, 'الشعراء', 'Ash-Shu‘arā’', 227, 'Meccan'),
    SurahInfo(27, 'النَّمل', 'An-Naml', 93, 'Meccan'),
    SurahInfo(28, 'القَصَص', 'Al-Qaṣaṣ', 88, 'Meccan'),
    SurahInfo(29, 'العَنكبُوت', 'Al-‘Ankabūt', 69, 'Meccan'),
    SurahInfo(30, 'الرُّوم', 'Ar-Rūm', 60, 'Meccan'),
    SurahInfo(31, 'لُقمَان', 'Luqmān', 34, 'Meccan'),
    SurahInfo(32, 'السَّجدة', 'As-Sajdah', 30, 'Meccan'),
    SurahInfo(33, 'الأحزَاب', 'Al-Aḥzāb', 73, 'Medinan'),
    SurahInfo(34, 'سَبإ', 'Saba’', 54, 'Meccan'),
    SurahInfo(35, 'فَاطِر', 'Fāṭir', 45, 'Meccan'),
    SurahInfo(36, 'يسٓ', 'Yā-Sīn', 83, 'Meccan'),
    SurahInfo(37, 'الصَّافَات', 'Aṣ-Ṣāffāt', 182, 'Meccan'),
    SurahInfo(38, 'صٓ', 'Ṣād', 88, 'Meccan'),
    SurahInfo(39, 'الزُّمَر', 'Az-Zumar', 75, 'Meccan'),
    SurahInfo(40, 'غَافِر', 'Ghāfir', 85, 'Meccan'),
    SurahInfo(41, 'فُصِّلَت', 'Fuṣṣilat', 54, 'Meccan'),
    SurahInfo(42, 'الشُّورى', 'Ash-Shūra', 53, 'Meccan'),
    SurahInfo(43, 'الزُّخرُف', 'Az-Zukhruf', 89, 'Meccan'),
    SurahInfo(44, 'الدُّخان', 'Ad-Dukhān', 59, 'Meccan'),
    SurahInfo(45, 'الجاثِية', 'Al-Jāthiyah', 37, 'Meccan'),
    SurahInfo(46, 'الأحقَاف', 'Al-Aḥqāf', 35, 'Meccan'),
    SurahInfo(47, 'مُحمد', 'Muḥammad', 38, 'Medinan'),
    SurahInfo(48, 'الفَتح', 'Al-Fatḥ', 29, 'Medinan'),
    SurahInfo(49, 'الحُجُرَات', 'Al-Ḥujurāt', 18, 'Medinan'),
    SurahInfo(50, 'قٓ', 'Qāf', 45, 'Meccan'),
    SurahInfo(51, 'الذَّاريَات', 'Adh-Dhāriyāt', 60, 'Meccan'),
    SurahInfo(52, 'الطُّور', 'Aṭ-Ṭūr', 49, 'Meccan'),
    SurahInfo(53, 'النَّجم', 'An-Najm', 62, 'Meccan'),
    SurahInfo(54, 'القَمَر', 'Al-Qamar', 55, 'Meccan'),
    SurahInfo(55, 'الرَّحمٰن', 'Ar-Raḥmān', 78, 'Medinan'),
    SurahInfo(56, 'الوَاقِعة', 'Al-Wāqi‘ah', 96, 'Meccan'),
    SurahInfo(57, 'الحدِيد', 'Al-Ḥadīd', 29, 'Medinan'),
    SurahInfo(58, 'المُجَادلة', 'Al-Mujādilah', 22, 'Medinan'),
    SurahInfo(59, 'الحَشر', 'Al-Ḥashr', 24, 'Medinan'),
    SurahInfo(60, 'المُمتَحنَة', 'Al-Mumtaḥanah', 13, 'Medinan'),
    SurahInfo(61, 'الصَّف', 'Aṣ-Ṣaff', 14, 'Medinan'),
    SurahInfo(62, 'الجُمعَة', 'Al-Jumu‘ah', 11, 'Medinan'),
    SurahInfo(63, 'المُنَافِقُونَ', 'Al-Munāfiqūn', 11, 'Medinan'),
    SurahInfo(64, 'التغَابُن', 'At-Taghābun', 18, 'Medinan'),
    SurahInfo(65, 'الطَّلَاق', 'Aṭ-Ṭalāq', 12, 'Medinan'),
    SurahInfo(66, 'التَّحرِيم', 'At-Taḥrīm', 12, 'Medinan'),
    SurahInfo(67, 'المُلك', 'Al-Mulk', 30, 'Meccan'),
    SurahInfo(68, 'القَلَم', 'Al-Qalam', 52, 'Meccan'),
    SurahInfo(69, 'الحَاقة', 'Al-Ḥāqqah', 52, 'Meccan'),
    SurahInfo(70, 'المَعَارج', 'Al-Ma‘ārij', 44, 'Meccan'),
    SurahInfo(71, 'نُوح', 'Nūḥ', 28, 'Meccan'),
    SurahInfo(72, 'الجِن', 'Al-Jinn', 28, 'Meccan'),
    SurahInfo(73, 'المُزمل', 'Al-Muzzammil', 20, 'Meccan'),
    SurahInfo(74, 'المُدثر', 'Al-Muddaththir', 56, 'Meccan'),
    SurahInfo(75, 'القِيَامة', 'Al-Qiyāmah', 40, 'Meccan'),
    SurahInfo(76, 'الإنسَان', 'Al-Insān', 31, 'Meccan'),
    SurahInfo(77, 'المُرسَلات', 'Al-Mursalāt', 50, 'Meccan'),
    SurahInfo(78, 'النَّبَإ', 'An-Naba’', 40, 'Meccan'),
    SurahInfo(79, 'النَّازعَات', 'An-Nāzi‘āt', 46, 'Meccan'),
    SurahInfo(80, 'عَبَسَ', '‘Abasa', 42, 'Meccan'),
    SurahInfo(81, 'التَّكوير', 'At-Takwīr', 29, 'Meccan'),
    SurahInfo(82, 'الانفِطَار', 'Al-Infiṭār', 19, 'Meccan'),
    SurahInfo(83, 'المُطَففين', 'Al-Muṭaffifīn', 36, 'Meccan'),
    SurahInfo(84, 'الانشِقَاق', 'Al-Inshiqāq', 25, 'Meccan'),
    SurahInfo(85, 'البُرُوج', 'Al-Burūj', 22, 'Meccan'),
    SurahInfo(86, 'الطَّارق', 'Aṭ-Ṭāriq', 17, 'Meccan'),
    SurahInfo(87, 'الأعلى', 'Al-A‘lā', 19, 'Meccan'),
    SurahInfo(88, 'الغَاشِية', 'Al-Ghāshiyah', 26, 'Meccan'),
    SurahInfo(89, 'الفَجر', 'Al-Fajr', 30, 'Meccan'),
    SurahInfo(90, 'البَلَد', 'Al-Balad', 20, 'Meccan'),
    SurahInfo(91, 'الشَّمس', 'Ash-Shams', 15, 'Meccan'),
    SurahInfo(92, 'اللَّيل', 'Al-Lail', 21, 'Meccan'),
    SurahInfo(93, 'الضُّحى', 'Aḍ-Ḍuḥā', 11, 'Meccan'),
    SurahInfo(94, 'الشَّرح', 'Ash-Sharḥ', 8, 'Meccan'),
    SurahInfo(95, 'التِّين', 'At-Tīn', 8, 'Meccan'),
    SurahInfo(96, 'العَلَق', 'Al-‘Alaq', 19, 'Meccan'),
    SurahInfo(97, 'القَدر', 'Al-Qadr', 5, 'Meccan'),
    SurahInfo(98, 'البَينَة', 'Al-Bayyinah', 8, 'Medinan'),
    SurahInfo(99, 'الزَّلزَلة', 'Az-Zalzalah', 8, 'Medinan'),
    SurahInfo(100, 'العَاديَات', 'Al-‘Ādiyāt', 11, 'Meccan'),
    SurahInfo(101, 'القَارعَة', 'Al-Qāri‘ah', 11, 'Meccan'),
    SurahInfo(102, 'التَّكاثُر', 'At-Takāthur', 8, 'Meccan'),
    SurahInfo(103, 'العَصر', 'Al-‘Aṣr', 3, 'Meccan'),
    SurahInfo(104, 'الهُمَزة', 'Al-Humazah', 9, 'Meccan'),
    SurahInfo(105, 'الفِيل', 'Al-Fīl', 5, 'Meccan'),
    SurahInfo(106, 'قُرَيش', 'Quraish', 4, 'Meccan'),
    SurahInfo(107, 'المَاعُون', 'Al-Mā‘ūn', 7, 'Meccan'),
    SurahInfo(108, 'الكَوثر', 'Al-Kauthar', 3, 'Meccan'),
    SurahInfo(109, 'الكافِرون', 'Al-Kāfirūn', 6, 'Meccan'),
    SurahInfo(110, 'النَّصر', 'An-Naṣr', 3, 'Meccan'),
    SurahInfo(111, 'المَسَد', 'Al-Masad', 5, 'Meccan'),
    SurahInfo(112, 'الإخلَاص', 'Al-Ikhlāṣ', 4, 'Meccan'),
    SurahInfo(113, 'الفَلَق', 'Al-Falaq', 5, 'Meccan'),
    SurahInfo(114, 'النَّاس', 'An-Nās', 6, 'Meccan'),
  ];
}

class SurahInfo {
  final int number;
  final String nameAr;
  final String nameEn;
  final int verseCount;
  final String type;

  const SurahInfo(this.number, this.nameAr, this.nameEn, this.verseCount, this.type);
}
